plugins {
	id 'java'
	id 'org.springframework.boot'			version "${springBootPluginVersion}"
	id 'io.spring.dependency-management'	version "${springDependencyManagementPluginVersion}"
}

group = 'com.jatheon.ergo.ai.assistant'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	implementation.exclude module: "spring-boot-starter-tomcat"
}

repositories {
	mavenCentral()
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
		mavenBom "org.springframework.boot:spring-boot-starter-parent:${springBootVersion}"
		mavenBom "com.fasterxml.jackson:jackson-bom:${jacksonVersion}"
		mavenBom "dev.langchain4j:langchain4j-bom:${langchain4jVersion}"
		mavenBom "software.amazon.awssdk:bom:${awsSdkVersion}"
	}
}

dependencies {
	implementation "me.paulschwarz:spring-dotenv:${springDotEnvVersion}"

	//~ Logback
	implementation "ch.qos.logback:logback-access:${logbackVersion}"
	implementation "ch.qos.logback:logback-core:${logbackVersion}"
	implementation "ch.qos.logback:logback-classic:${logbackVersion}"

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.data:spring-data-commons'

	//~ Thymeleaf
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

	//~ Undertow servlet
	implementation 'org.springframework.boot:spring-boot-starter-undertow'
	implementation "io.undertow:undertow-servlet:${undertowVersion}"
	implementation "io.undertow:undertow-core:${undertowVersion}"

	//~ Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	//~ Apache Commons
	implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
	implementation "commons-codec:commons-codec:${commonsCodecsVersion}"

	//~ JSON
	implementation 'com.fasterxml.jackson.core:jackson-core'
	implementation 'com.fasterxml.jackson.core:jackson-annotations'
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	implementation "com.google.code.gson:gson:${gsonVersion}"

	//~ dev.langchain4j
	implementation 'dev.langchain4j:langchain4j'
	implementation 'dev.langchain4j:langchain4j-document-loader-amazon-s3'
	implementation 'dev.langchain4j:langchain4j-document-parser-apache-tika'
	implementation 'dev.langchain4j:langchain4j-document-parser-apache-pdfbox'
	implementation 'dev.langchain4j:langchain4j-document-parser-apache-poi'
	implementation 'dev.langchain4j:langchain4j-open-ai'
	implementation 'dev.langchain4j:langchain4j-embeddings'
	implementation 'dev.langchain4j:langchain4j-elasticsearch'

	//~ AWS
	implementation 'software.amazon.awssdk:s3'
	implementation 'software.amazon.awssdk:s3-event-notifications'
	implementation 'software.amazon.awssdk:sqs'
	implementation 'software.amazon.awssdk:url-connection-client'

	//~ Elasticsearch
	implementation "co.elastic.clients:elasticsearch-java:${elasticsearchVersion}"

	//~ WebJARs Locator
	implementation "org.webjars:webjars-locator-core:${webjarsLocatorVersion}"

	//~ WebJars : Bootstrap v5.x, jQuery 3.7.x
	implementation "org.webjars:bootstrap:${webjarsBootstrapVersion}"
	implementation "org.webjars:jquery:${webjarsJQueryVersion}"
	implementation "org.webjars.npm:bootstrap-icons:${webjarsBootstrapIconsVersion}"

	//~ testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootRun {
	systemProperties = System.properties
	args = ["--spring.profiles.active=dev"]
	jvmArgs = [
			"-Duser.language=en",
			"-Duser.region=US"
	]
}

